simulation : distribution.c file.c init_for_next.c list.c main.c make_ad_list.c rewiring_network.c set_edge.c set_firstInf.c set_value.c source_reset.c spreading_theories.c
						gcc distribution.c file.c init_for_next.c list.c main.c make_ad_list.c rewiring_network.c set_edge.c set_firstInf.c set_value.c source_reset.c spreading_theories.c -o simulation -lm
